markdown: rdiscount
auto: true
pygments: true
url: http://tiemuxu.github.com
paginate: 10
title: Front Wind
years:
- "2008"
- "2009"
- "2010"
- "2011"
- "2012"
- "2013"
main_menu:
- label: Home
  url: /index.html
- label: 前端
  url: /frontend.html
- label: 翻译
  url: /translation.html
- label: 随笔
  url: /essay.html
- label: 关于
  url: /about.html